project_id = "vfzyodedgtefvxcrqdtc"

[functions.create-admin-user]
verify_jwt = false

[functions.admin-reset-employee-password]
verify_jwt = true

[functions.compliance-automation]
verify_jwt = false

[functions.compliance-data-archival]
verify_jwt = false

[functions.get-reference-request]
verify_jwt = false

[functions.submit-reference]
verify_jwt = false

[functions.send-reference-email]
verify_jwt = true